# Generated by Django 5.0.7 on 2024-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('oval', 'Oval')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
